// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3CN7yA3Vmo0ulgJekn4EQTJVAmVLjTvI',
    appId: '1:394381446954:web:31c151b4953cbc2ef51853',
    messagingSenderId: '394381446954',
    projectId: 'chatx-8af67',
    authDomain: 'chatx-8af67.firebaseapp.com',
    storageBucket: 'chatx-8af67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyuFa5gKoCHLc6wUFJ0jZIFouLN5sZRuI',
    appId: '1:394381446954:android:0d26736b9dabac8df51853',
    messagingSenderId: '394381446954',
    projectId: 'chatx-8af67',
    storageBucket: 'chatx-8af67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB86ubQzQxh4cSA6bTYT5cHqzMu2JNRyF8',
    appId: '1:394381446954:ios:5d2d0ed61687a705f51853',
    messagingSenderId: '394381446954',
    projectId: 'chatx-8af67',
    storageBucket: 'chatx-8af67.appspot.com',
    iosBundleId: 'com.example.chatx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB86ubQzQxh4cSA6bTYT5cHqzMu2JNRyF8',
    appId: '1:394381446954:ios:59d7e5dbd70b4bfbf51853',
    messagingSenderId: '394381446954',
    projectId: 'chatx-8af67',
    storageBucket: 'chatx-8af67.appspot.com',
    iosBundleId: 'com.example.chatx.RunnerTests',
  );
}
